CHAPTER 15

THE C COMPILER IS THE ORIGION OF PROGRAMING, FOLLOWING TRADITIONAL PROCESS 
WRITE PROGRAM, COMPILE THEM THEN RUN THEM. UNIX USES GNU C COMPILER, 
C PROGRAMS ARE TO LARAGE INSIDE EACH SINGLE SOURCE, THAT'S MAKES THEM DISORGINIZED 
THEREFORE, THE DEVELOPERS ORGANIZED THEM IN THERE OWN FILES. THE PROGRAMS DIVIDED INT TWO 
SECTIONS, HEADER, ADDITIONAL SOURCE CODE CONTAIN LIBRARY SUCH AS, STDIO.H.
HOWEVER, SOME PROGRAMMERS FORGET TO INCLUDE THE REQUIRED HEADER.
MOREOVER, SOMETIMES THERE ARE MANY INCLUDE FILE WITH THE SAME NAME WHAT MAKE
HARD TO TRACK THEM OR CHOOSE THE CORRECT ONE.THE C PROGRAM CONTAIN CPP  
WHICH IS RESPONSIBLE TO LOOK FOR INCLUDE FILES.ALSO YOU NEED TO BUILD LIBRARIES TO 
CREATE COMPLETE PROGRAMS. WITCH THEY ARE COLLECTION OF PRECOMPILED FUNCTIONS,
THAT WE CAN BUILD INTO OUR PROGRAM. IF THE PROGRAM COUDN'T FIND A FUNCTON
WILL DISPLAY ERROR MESSAGE IN BOLD, THAT'S THE MOST IMPORTANT ERRORS.THERE
ARE DIFFERENT KINDS LIBRARIES STATIC LIBRARY WHICH ENDS WITH .a, AND INSECURE
LIBRARY AND BOTH ARE SHARED LIBRARIES. THE TWO STANDERD LIBRARIES IN LINUX
/LIB AND /USR/LIB.ID.SO THE FILE THAT'S LOCATE THE SHARE LIBRARIES, BUT ONE OF THE COMMON 
PROBLEMS FOR SHARED LIBRARIES IS THE DYNAMIC LINKER CAN'T FIND LIBRARIES.
FIRST THEY SEARCH IN THE PRECONFIG IF THEY FOUNF IT YOU WILL SEE IT, OTHERWISE 
WILL LOOK IN SYSTEM CACHE. 
UNIX RELY ON UTILITY CALLED "MAKE" TO SOLVE SOME COMPILER PROBLEM AN EXAMPLE 
FOR MAKEFILE A PROGRAM CALLED MYPROG FROM AUX.C OR MAIN.C. MAKE FOLLOW THE
BUILT-IN RULES SO IT KNOWS TO A.C WHEN YOU NEED O.C, THE FNAL STEP OF GETTING 
PROGRAM IS AFTER YOU CREATE THE TWO OBJECTS FILES YOU CAN RUN THE COMPILER.
TO ORGANIZE THE MAKE FILES YOU SHOULD SEE THE LIBRARIES AND INCLUDES GROUPED 
ACCORDING TO THE PACKAGE. ALSO YOU CAN COMBINE TWO EXECUTABLE TARGETS IN 
ONE RULE. 
LEX & YACC:-
LEX IS A TOKENIZER THAT TRANSFORMS TEXT INTI NUMBERS TAGS WITH LABELS.
YACC IS A PARSER THAT ATTEMP TO READ TOKENS ACCORDING TO GRAMMAR.
OTHER LINUX SCRIPTING LANGUAGES:-
PYTHON, PERL, JAVA..... .

-------------

CHAPTER 14

    First thing we should do is to update and upgrade the repository. Ubuntu uses (apt-get) for its package manager I will be using it here. The following command updates the repository: apt-get update [Make sure to run all this commands as sudo if not logged in as root]
    Search for all the packages that have the name awesome with this command: apt-cache search awesome
    The one you want to install should say this: awesome - highly configurable X window manager
    If this option shows up after you run the command on step 2, Everything is going good for you. If you don't get this results make sure you are connected to the Internet.
    To install awesome we will run the proper command using sudo rights: apt-get install awesome This will take some time so let it do its thing.
    Once installed, you can reboot or log out of your current session. To get back to the log in screen.
    On the log in screen you see a window that displays your user name on one corner and a tiny Ubuntu logo on the other. Click on this logo. The window now reads Select Desktop Environment
    Choose the one that reads awesome.
    Log In, you are now presented with the awesome window environment..HAVEFUN!


